[package]
name = "RECallS"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
eyre = "0.6.14"
itertools = "0.15.0"
log = "0.4.34"
noodles = { version = "*", features = ["bam", "bgzf", "core", "fasta", "sam"] }
rammap-core = "1.1.2"
rust-lapper = "2.0.0-beta.1"
scirs2-integrate = "0.6.5"
scirs2-stats = "0.6.5"
